# Generated by Django 5.2.8 on 2025-12-01 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='meals/')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in PKR', max_digits=10)),
                ('quantity_available', models.PositiveIntegerField(default=1)),
                ('ready_time', models.TimeField(help_text='Time when meal will be ready')),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval status')),
                ('is_active', models.BooleanField(default=True, help_text='Is meal currently available')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='accounts.cookprofile')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
