# Generated by Django 5.2.7 on 2025-12-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='dine_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for dine-in (PKR)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='dine_with_us_available',
            field=models.BooleanField(default=False, help_text='Allow customers to dine at your place'),
        ),
    ]
