# Generated by Django 5.2.7 on 2025-12-05 17:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('meals', '0002_meal_dine_price_meal_dine_with_us_available'),
        ('orders', '0003_alter_order_delivery_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_rating', models.PositiveIntegerField(help_text='Rating for the meal (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cook_rating', models.PositiveIntegerField(help_text='Rating for the cook (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional review comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='accounts.cookprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='accounts.customerprofile')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='meals.meal')),
                ('order', models.OneToOneField(help_text='The order being rated', on_delete=django.db.models.deletion.CASCADE, related_name='rating_detail', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'order')},
            },
        ),
    ]
