# Generated by Django 5.2.7 on 2025-12-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='office_location_lat',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='office_location_lng',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='customer_type',
            field=models.CharField(choices=[('office_worker', 'Office Worker'), ('hostel_student', 'Hostel Student')], default='office_worker', help_text='Are you an office worker or hostel student?', max_length=20),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='location_address',
            field=models.TextField(blank=True, help_text='Office address or hostel name/location'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Office or hostel latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Office or hostel longitude', max_digits=9, null=True),
        ),
    ]
