# Generated by Django 5.2.7 on 2025-12-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='Rating from 1 to 5', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='review',
            field=models.TextField(blank=True, help_text='Customer review'),
        ),
    ]
