# Generated by Django 5.2.7 on 2025-12-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_rating_order_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('dine_in', 'Dine-In')], default='pickup', max_length=20),
        ),
    ]
